---
- name: Deploy Dynatrace OneAgent using the Dynatrace OneAgent role
  hosts: all
  vars:
    oneagent_environment_url: "{{ dynatrace_url }}"
    oneagent_paas_token: "{{ dynatrace_token }}"
  tasks:
    - name: Import Dynatrace OneAgent role
      ansible.builtin.import_role:
        name: dynatrace.oneagent.oneagent